name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sudo apt-get install cmake libjpeg8-dev gcc g++
    - name: make
      run: make
    
    - name: Upload Artifact:
      uses: actions/upload-artifact@4.0
      with:
        path: ./
    
        if-no-files-found: error # optional, default is warn
        
        overwrite: true # optional, default is false
        # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.
    
        include-hidden-files: true # optional, default is false
                
